luna_cost_management:
    resource: "@LunaCostManagementBundle/Resources/config/routing.yml"
    prefix:   /

luna_reception:
    resource: "@LunaReceptionBundle/Resources/config/routing.yml"
    prefix:   /

luna_user:
    resource: "@LunaUserBundle/Resources/config/routing.yml"
    prefix:   /